---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь авторизоваться на сайте с помощью Git 
  - Авторизованный пользователь должен иметь возможность входить на сайт
  - Авторизованный пользователь должен иметь возможность восстанавливать пароль
  - Пользователь может отправлять пользователям в сети личное сообщение
  - Пользователь может отправлять сообщения в общий чат
  - Пользователь может отправлять приглашения на игру 
  - Пользователь должен иметь возможность начать новую игру
  - Пользователь должен иметь возможность создать игру с ботом
  - Пользователь должен иметь возможность создать игру с пользователями в сети
  - Пользователь должен иметь возможность создать игру с другом
  - Пользователь должен иметь возможность задавать уровень игры
  - Пользователь должен иметь возможность задавать таймер игры
  - Пользователь должен иметь возможность выбирать задачу по названию
  - Пользователь должен иметь возможность выбирать задачу по тегам
  - Пользователь должен иметь возможность отправлять другим пользователям приглашения
  - Пользователь должен иметь возможность принять приглашение на игру 
  - Пользователь должен иметь возможность отклонить приглашение на игру 
  - Пользователь должен иметь возможность выбрать язык программирования для игры
  - Пользователь должен иметь возможность писать в редакторе код задачи
  - Пользователь должен иметь возможность сбросить написанный код
  - Пользователь должен иметь возможность проверить решение
  - Пользователь должен иметь возможность просматривать результат проверки решения
  - Пользователь должен иметь возможность сдаться во время игры 
  - Пользователь должен иметь возможность взять матч-реванш после проигрыша
  - В случае победы пользователю должен быть присужден 1 балл
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен отображать таблицу лидеров
  - Сайт должен отображать список всех задач
  - Пользователь может просматривать ход текущей игры
  - Сайт должен отображать расписание предстоящих турниров
  - Пользователь должен иметь возможность просматривать свой профиль
  - Пользователь должен иметь возможность настраивать свой профиль
  - Пользователь должен иметь возможность просматривать профили других пользователей 
  - Сайт должен отображать приглашения, отправленные другими пользователями
  - Сайт должен отображать инструкцию перед началом игры
  - Сайт должен отображать задачу на 2-х языках: английском и русском
  - Сайт должен оповещать пользователя, в случае победы или проигрыша
implicit:
  - При нажатии на кнопку Codebattle происходит переход на главную страницу из любой вкладки
  - Пользователь не может вносить изменения в условия задач, представленных на сайте
  - Пользователь может добавлять новые задачи от своего имени
